[package]
name = "protoc-gen-typescript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "3.2"
swc = { git = "https://github.com/swc-project/swc" }
num-bigint = "0.4.3"
