name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt, clippy

    - name: Check Format
      run: cargo fmt --check

    - name: Lint
      run: cargo clippy

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Install
      run: echo target/debug >> $GITHUB_PATH

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Generate code
      run: |
        mkdir out
        protoc -Iexample --typescript_out=out example/test.proto

    - name: Upload generated code
      uses: actions/upload-artifact@v3
      with:
        name: generated-code
        path: out
